# Generated by Django 4.0.4 on 2022-04-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=250, null=True)),
                ('Address', models.TextField(null=True)),
                ('LastName', models.CharField(max_length=250, null=True)),
                ('EmailAddress', models.CharField(max_length=250, null=True)),
                ('Date', models.DateField(null=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('ModiefiedTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
